manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/cdc-mkb
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: mouse-pim447
      import: app/west.yml
---
include:
  - board: nice_nano_v2
    shield: sofle_left nice_oled
  - board: nice_nano_v2
    shield: sofle_right nice_oled
  - board: nice_nano_v2
    shield: settings_reset