include:
  - board: nice_nano_v2
    shield: sofle_right nice_oled
    snippet: zmk-usb-logging
    cmake-args: >
      -DBOARD_ROOT=${GITHUB_WORKSPACE}/zmk/app
      -DZEPHYR_EXTRA_MODULES="${GITHUB_WORKSPACE}/pim447_custom;${GITHUB_WORKSPACE}/zmk-nice-oled"
      -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
      -DDTC_OVERLAY_FILE="${GITHUB_WORKSPACE}/config/sofle_right.overlay"
  - board: nice_nano_v2
    shield: sofle_left nice_oled
  - board: nice_nano_v2
    shield: settings_reset