include:
  - board: nice_nano_v2
    shield: sofle_right nice_oled
    snippet: zmk-usb-logging
    cmake-args: >
      -DBOARD_ROOT=${GITHUB_WORKSPACE}/zmk/app
      -DZEPHYR_EXTRA_MODULES="${GITHUB_WORKSPACE}/pim447;${GITHUB_WORKSPACE}/zmk-nice-oled;${GITHUB_WORKSPACE}/kconfig_patch"
  - board: nice_nano_v2
    shield: sofle_left nice_oled
  - board: nice_nano_v2
    shield: settings_reset