include:
  - board: nice_nano_v2
    shield: sofle_right nice_oled
    snippet: zmk-usb-logging
    cmake-args: >
      -DBOARD_ROOT=${GITHUB_WORKSPACE}/zmk/app
      -DZEPHYR_EXTRA_MODULES="${GITHUB_WORKSPACE}/pim447;${GITHUB_WORKSPACE}/zmk-nice-oled;${GITHUB_WORKSPACE}/kconfig_patch"
      -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
      -DCONFIG_ZMK_USB=y
      -DCONFIG_I2C=y
      -DCONFIG_ZMK_POINTING=y
      -DCONFIG_ZMK_MOUSE=y
      -DCONFIG_LOG=y
      -DCONFIG_ZMK_LOG_LEVEL_INF=y
      -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
      -DCONFIG_SHELL=y
      -DCONFIG_SHELL_BACKEND_SERIAL=y
      -DCONFIG_I2C_SHELL=y
      -DCONFIG_UART_LINE_CTRL=y
      -DCONFIG_SENSOR_SHELL=n
      -DCONFIG_SHELL_BACKEND_SERIAL_RX_RING_BUFFER_SIZE=2048
      -DCONFIG_SHELL_BACKEND_SERIAL_TX_RING_BUFFER_SIZE=4096
  - board: nice_nano_v2
    shield: sofle_left nice_oled
  - board: nice_nano_v2
    shield: settings_reset