include:
  - board: nice_nano_v2
    shield: sofle_right nice_oled         # o solo "sofle_right" si prefieres sin OLED
    snippet: zmk-usb-logging              # crea un puerto COM por USB
    cmake-args: >                         # habilita logs y shell (temporal para depurar)
      -DCONFIG_LOG=y
      -DCONFIG_ZMK_LOG_LEVEL_DBG=y
      -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
      -DCONFIG_SHELL=y
      -DCONFIG_SHELL_BACKEND_SERIAL=y
      -DCONFIG_I2C_SHELL=y
      -DCONFIG_UART_LINE_CTRL=y

  - board: nice_nano_v2
    shield: sofle_left nice_oled

  - board: nice_nano_v2
    shield: settings_reset