include:
  - board: nice_nano_v2
    shield: sofle_right nice_oled
    snippet: zmk-usb-logging
    cmake-args: >
      -DCONFIG_LOG=y
      -DCONFIG_ZMK_LOG_LEVEL_INF=y
      -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
      -DCONFIG_SHELL=y
      -DCONFIG_SHELL_BACKEND_SERIAL=y
      -DCONFIG_I2C_SHELL=y
      -DCONFIG_UART_LINE_CTRL=y
      -DCONFIG_SENSOR_SHELL=n
      -DCONFIG_SHELL_BACKEND_SERIAL_RX_RING_BUFFER_SIZE=2048
  - board: nice_nano_v2
    shield: sofle_left nice_oled
  - board: nice_nano_v2
    shield: settings_reset