include:
  - board: nice_nano_v2
    shield: sofle_left nice_oled
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_MOUSE=y
  - board: nice_nano_v2
    shield: sofle_right nice_oled
    cmake-args: -DCONFIG_ZMK_MOUSE=y
  - board: nice_nano_v2
    shield: settings_reset