manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: microsoft
      url-base: https://github.com/microsoft
    - name: cdc-mkb
      url-base: https://github.com/cdc-mkb

  projects:
    - name: zephyr
      remote: zmkfirmware
      revision: v2.5.0+zmk-fixes
      clone-depth: 1
      import:
        name-blacklist:
          - ci-tools
          - hal_altera
          - hal_cypress
          - hal_infineon
          - hal_microchip
          - hal_nxp
          - hal_openisa
          - hal_silabs
          - hal_xtensa
          - hal_st
          - hal_ti
          - loramac-node
          - mcuboot
          - mcumgr
          - net-tools
          - segger
          - openthread
          - edtt
          - trusted-firmware-m

    - name: uf2
      remote: microsoft
      path: tools/uf2
      clone-depth: 1

    - name: zmk
      remote: cdc-mkb
      revision: mouse-pim447
      import: app/west.yml

  self:
    west-commands: scripts/west-commands.yml
