# config/pimoroni,pim447_trackball.yaml
# IMPORTANTE: Nombre del archivo debe ser pimoroni,pim447_trackball.yaml (con guión bajo)

description: Pimoroni PIM447 I2C trackball

compatible: "pimoroni,pim447_trackball"

include: [i2c-device.yaml]

properties:
  label:
    type: string
    required: true
    
  reg:
    required: true
    
  drdy-gpios:
    type: phandle-array
    required: false
    description: Data ready GPIO pin
    
  mode:
    type: int
    default: 0
    description: |
      Operating mode
      0 = PIM447_MOVE (pointer mode, default)
      1 = PIM447_SCROLL (scroll mode)
      
  invert-move-x:
    type: boolean
    description: Invert X axis for pointer movement
    
  invert-move-y:
    type: boolean
    description: Invert Y axis for pointer movement
    
  invert-scroll-x:
    type: boolean
    description: Invert X axis for scroll
    
  invert-scroll-y:
    type: boolean
    description: Invert Y axis for scroll
    
  swap-axes:
    type: boolean
    description: Swap X and Y axes
    
  move-factor:
    type: int
    default: 1
    description: Multiplier for pointer speed
    
  scroll-divisor:
    type: int
    default: 2
    description: Divider for scroll speed
    
  button:
    type: int
    default: 0
    description: Mouse button number generated by ball press