manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
    - name: cdc-mkb
      url-base: https://github.com/cdc-mkb
  projects:
    # Usamos el fork de cdc-mkb que tiene soporte para Pimoroni
    - name: zmk
      remote: cdc-mkb
      revision: mouse-pim447
      import: app/west.yml
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main
  self:
    path: config