name: ZMK Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Debug repo layout
        run: |
          pwd
          ls -R | grep gen_kobject_list.py || true

      - name: Fix Python distutils issue
        run: |
          apt-get update
          apt-get install -y python3-pip
          pip3 install packaging --break-system-packages
          # Buscar y parchear el archivo en cualquier ubicación
          find . -name "gen_kobject_list.py" -type f -exec sed -i 's/from distutils.version import LooseVersion/from packaging.version import Version as LooseVersion/' {} \;
        
      - name: Clean zmk folder
        run: rm -rf zmk
        
      - name: West Init
        run: west init -l config
        
      - name: West Update
        run: west update
        
      - name: Apply local ZMK changes
        run: |
          echo "=== Aplicando cambios locales al fork ==="
          cp -r ${GITHUB_WORKSPACE}/zmk/app/include/dt-bindings/zmk/trackball_pim447.h zmk/app/include/dt-bindings/zmk/
          cp ${GITHUB_WORKSPACE}/zmk/app/boards/shields/sofle/sofle_left.overlay zmk/app/boards/shields/sofle/
          echo "✅ Cambios aplicados"
        
      - name: Debug - Check ZMK remote
        run: |
          cd zmk
          git remote -v
          git rev-parse --abbrev-ref HEAD
        
      - name: Debug - Check for PIM447 driver
        run: |
          ls -R zmk/drivers | grep pim447 || echo "PIM447 driver not found"
        
      - name: West Zephyr export
        run: west zephyr-export
        
      - name: Debug - Check overlays
        run: |
          echo "=== Overlays encontrados ==="
          find ${GITHUB_WORKSPACE}/config -name "*.overlay" -type f
          echo "=== Contenido del overlay sofle ==="
          cat ${GITHUB_WORKSPACE}/config/boards/shields/sofle/sofle.overlay || true

      - name: Build LEFT (with PIM447)
        run: |
          west build -s zmk/app -b nice_nano_v2 -d build/left -- \
            -DSHIELD="sofle_left" \
            -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
        
      - name: Build RIGHT (with OLED)
        run: |
          west build -s zmk/app -b nice_nano_v2 -d build/right -- \
            -DSHIELD="sofle_right nice_oled" \
            -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
        
      - name: Verify PIM447
        run: |
          echo "=== Verificando PIM447 ==="
          if [ -f build/left/zephyr/zephyr.dts ]; then
            grep -n "pim447" build/left/zephyr/zephyr.dts && echo "✅ PIM447 encontrado" || echo "❌ PIM447 no encontrado"
          else
            echo "DTS file not found"
          fi
        
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/left/zephyr/zmk.uf2
            build/right/zephyr/zmk.uf2