name: ZMK Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Zephyr dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            git cmake ninja-build gperf \
            ccache dfu-util device-tree-compiler \
            python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
            make gcc gcc-multilib g++-multilib libsdl2-dev
          
          pip3 install west
          
      - name: Setup Zephyr environment
        run: |
          # Usar Zephyr que viene con el fork de ZMK (debería ser 3.x)
          echo "ZEPHYR_BASE=${GITHUB_WORKSPACE}/zephyr" >> $GITHUB_ENV
          echo "ZEPHYR_TOOLCHAIN_VARIANT=zephyr" >> $GITHUB_ENV
        
      - name: Clean zmk folder
        run: rm -rf zmk
        
      - name: West Init
        run: west init -l config
        
      - name: West Update
        run: west update
        
      - name: Install Zephyr SDK
        run: |
          # Instalar Zephyr SDK más pequeño (solo arm)
          wget -q https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.1/zephyr-sdk-0.16.1_linux-x86_64.tar.xz
          tar xf zephyr-sdk-0.16.1_linux-x86_64.tar.xz
          cd zephyr-sdk-0.16.1
          ./setup.sh -t arm-zephyr-eabi
          cd ..
          echo "ZEPHYR_SDK_INSTALL_DIR=\"\${GITHUB_WORKSPACE}/zephyr-sdk-0.16.1\"" >> $GITHUB_ENV
        
      - name: Patch PIM447 bindings and driver
        run: |
          echo "=== Copiando binding YAML ==="
          mkdir -p zmk/app/dts/bindings/sensor/
          cp config/pimoroni,trackball_pim447.yaml zmk/app/dts/bindings/sensor/
          echo "✅ Binding YAML copiado"

          echo "=== Verificando drivers PIM447 ==="
          echo "Buscando drivers en zmk/app/..."
          find ./zmk -name "*pim447*" -o -name "*trackball*" -type f
          
          echo "=== Directorios de drivers existentes ==="
          find ./zmk -name "src" -o -name "drivers" -type d
          
          echo "⚠️  Drivers PIM447 no encontrados - el trackball no funcionará"
          echo "Se necesita agregar manualmente los archivos trackball_pim447.c al fork de ZMK"
        
      - name: Verify ZMK custom files
        run: |
          echo "=== Verificando archivos personalizados ==="
          # Verificar que los archivos necesarios existen en el fork
          if [ -f zmk/app/dts/bindings/sensor/pimoroni,trackball_pim447.yaml ]; then
            echo "✅ pimoroni,trackball_pim447.yaml encontrado"
          else
            echo "❌ pimoroni,trackball_pim447.yaml no encontrado"
            exit 1
          fi
          
          if [ -f config/boards/shields/sofle/sofle_left.overlay ]; then
            echo "✅ sofle_left.overlay encontrado"
            echo "=== Contenido completo del overlay ==="
            cat config/boards/shields/sofle/sofle_left.overlay
          else
            echo "❌ sofle_left.overlay no encontrado"
            exit 1
          fi
        
      - name: Debug - Check ZMK remote
        run: |
          cd zmk
          git remote -v
          git rev-parse --abbrev-ref HEAD
        
      - name: Debug - Check for PIM447 driver
        run: |
          ls -R zmk/drivers | grep pim447 || echo "PIM447 driver not found"
        
      - name: West Zephyr export
        run: west zephyr-export
        
      - name: Debug - Check overlays
        run: |
          echo "=== Overlays encontrados ==="
          find ${GITHUB_WORKSPACE}/config -name "*.overlay" -type f
          echo "=== Contenido del overlay sofle ==="
          cat ${GITHUB_WORKSPACE}/config/boards/shields/sofle/sofle.overlay || true

      - name: Build LEFT (with PIM447)
        run: |
          west build -s zmk/app -b nice_nano_v2 -d build/left -- \
            -DSHIELD="sofle_left" \
            -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
        
      - name: Build RIGHT (with OLED)
        run: |
          west build -s zmk/app -b nice_nano_v2 -d build/right -- \
            -DSHIELD="sofle_right" \
            -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
        
      - name: Verify PIM447
        run: |
          echo "=== Verificando PIM447 ==="
          if [ -f build/left/zephyr/zephyr.dts ]; then
            grep -n "pimoroni,trackball_pim447" build/left/zephyr/zephyr.dts && echo "✅ PIM447 encontrado" || echo "❌ PIM447 no encontrado"
          else
            echo "DTS file not found"
          fi
        
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/left/zephyr/zmk.uf2
            build/right/zephyr/zmk.uf2