name: ZMK Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    
    steps:
      - name: Clean workspace cache
        run: echo "CACHE_BUSTER=$(date +%s)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Debug repo layout
        run: |
          pwd
          ls -R | grep gen_kobject_list.py || true

      - name: Fix Python distutils issue
        run: |
          apt-get update
          apt-get install -y python3-pip
          pip3 install packaging --break-system-packages
          # Buscar y parchear el archivo en cualquier ubicación
          find . -name "gen_kobject_list.py" -type f -exec sed -i 's/from distutils.version import LooseVersion/from packaging.version import Version as LooseVersion/' {} \;
        
      - name: Clean zmk folder
        run: rm -rf zmk
        
      - name: West Init
        run: west init -l config
        
      - name: West Update
        run: west update
        
      - name: Patch PIM447 bindings and driver
        run: |
          echo "=== Copiando binding YAML ==="
          mkdir -p zmk/app/dts/bindings/sensor/
          cp config/pimoroni,trackball_pim447.yaml zmk/app/dts/bindings/sensor/
          echo "✅ Binding YAML copiado"

          echo "=== Parcheando driver para Zephyr 2.5 ==="
          if [ -f zmk/app/src/mouse/trackball_pim447.c ]; then
            # Parchear mode
            sed -i 's/static int mode = DT_PROP(DT_INST(0, pimoroni_trackball_pim447), mode);/static int mode = 0; \/\* default mode *\//' zmk/app/src/mouse/trackball_pim447.c
            
            # Parchear label
            sed -i 's/const char \*label = DT_LABEL(DT_INST(0, pimoroni_trackball_pim447));/const char *label = "PIM447_TRACKBALL"; \/\* hardcoded *\//' zmk/app/src/mouse/trackball_pim447.c
            
            # Parchear booleanos
            sed -i 's/#define SWAP_AXES DT_PROP(DT_INST(0, pimoroni_trackball_pim447), swap_axes)/#define SWAP_AXES 0/' zmk/app/src/mouse/trackball_pim447.c
            sed -i 's/#define INVERT_MOVE_X DT_PROP(DT_INST(0, pimoroni_trackball_pim447), invert_move_x)/#define INVERT_MOVE_X 0/' zmk/app/src/mouse/trackball_pim447.c
            sed -i 's/#define INVERT_MOVE_Y DT_PROP(DT_INST(0, pimoroni_trackball_pim447), invert_move_y)/#define INVERT_MOVE_Y 0/' zmk/app/src/mouse/trackball_pim447.c
            sed -i 's/#define INVERT_SCROLL_X DT_PROP(DT_INST(0, pimoroni_trackball_pim447), invert_scroll_x)/#define INVERT_SCROLL_X 0/' zmk/app/src/mouse/trackball_pim447.c
            sed -i 's/#define INVERT_SCROLL_Y DT_PROP(DT_INST(0, pimoroni_trackball_pim447), invert_scroll_y)/#define INVERT_SCROLL_Y 0/' zmk/app/src/mouse/trackball_pim447.c
            
            # Propiedades booleanas -> hardcode a 0 (patrón amplio)
            sed -i 's/#define MOVE_X_INVERT.*/#define MOVE_X_INVERT 0/' zmk/app/src/mouse/trackball_pim447.c
            sed -i 's/#define MOVE_Y_INVERT.*/#define MOVE_Y_INVERT 0/' zmk/app/src/mouse/trackball_pim447.c
            sed -i 's/#define SCROLL_X_INVERT.*/#define SCROLL_X_INVERT 0/' zmk/app/src/mouse/trackball_pim447.c
            sed -i 's/#define SCROLL_Y_INVERT.*/#define SCROLL_Y_INVERT 0/' zmk/app/src/mouse/trackball_pim447.c
            
            # Parchear int properties
            sed -i 's/#define MOVE_FACTOR.*DT_PROP(DT_INST(0, pimoroni_trackball_pim447), move_factor)/#define MOVE_FACTOR 1/' zmk/app/src/mouse/trackball_pim447.c
            sed -i 's/#define SCROLL_DIVISOR.*DT_PROP(DT_INST(0, pimoroni_trackball_pim447), scroll_divisor)/#define SCROLL_DIVISOR 2/' zmk/app/src/mouse/trackball_pim447.c

            # Parche extra: eliminar DT_PROP para button
            sed -i 's/#define BUTTON.*/#define BUTTON 0/' zmk/app/src/mouse/trackball_pim447.c

            # Parche para dirección I2C hardcodeada (Zephyr 2.5 compatibility)
            sed -i 's/DT_INST_REG_ADDR(0)/0x0a/' zmk/app/src/mouse/trackball_pim447.c
            sed -i 's/DT_INST_REG_ADDR(0)/0x0a/' zmk/app/drivers/sensor/trackball_pim447/trackball_pim447.c 2>/dev/null || echo "⚠️  Driver sensor no encontrado, continuando..."

            # Parche para bus I2C hardcodeado (Zephyr 2.5 compatibility)
            sed -i 's/DT_INST_BUS_LABEL(0)/"I2C_0"/' zmk/app/src/mouse/trackball_pim447.c
            sed -i 's/DT_INST_BUS_LABEL(0)/"I2C_0"/' zmk/app/drivers/sensor/trackball_pim447/trackball_pim447.c 2>/dev/null || echo "⚠️  Driver sensor no encontrado, continuando..."

            echo "✅ Driver parcheado para Zephyr 2.5 (mode=0, label, booleanos=0, move_factor=1, scroll_divisor=2, i2c_addr=0x0a, i2c_bus=I2C_0)"
          else
            echo "⚠️  Driver no encontrado, puede que falle la compilación"
          fi
        
      - name: Verify ZMK custom files
        run: |
          echo "=== Verificando archivos personalizados ==="
          # Verificar que los archivos necesarios existen en el fork
          if [ -f zmk/app/include/dt-bindings/zmk/trackball_pim447.h ]; then
            echo "✅ trackball_pim447.h encontrado"
          else
            echo "❌ trackball_pim447.h no encontrado"
            exit 1
          fi
          
          if [ -f zmk/app/dts/bindings/sensor/pimoroni,trackball_pim447.yaml ]; then
            echo "✅ pimoroni,trackball_pim447.yaml encontrado"
          else
            echo "❌ pimoroni,trackball_pim447.yaml no encontrado"
            exit 1
          fi
          
          if [ -f config/boards/shields/sofle/sofle_left.overlay ]; then
            echo "✅ sofle_left.overlay encontrado"
            echo "=== Contenido del overlay ==="
            grep -n "mode\|compatible" config/boards/shields/sofle/sofle_left.overlay || true
          else
            echo "❌ sofle_left.overlay no encontrado"
            exit 1
          fi
        
      - name: Debug - Check ZMK remote
        run: |
          cd zmk
          git remote -v
          git rev-parse --abbrev-ref HEAD
        
      - name: Debug - Check for PIM447 driver
        run: |
          ls -R zmk/drivers | grep pim447 || echo "PIM447 driver not found"
        
      - name: West Zephyr export
        run: west zephyr-export
        
      - name: Debug - Check overlays
        run: |
          echo "=== Overlays encontrados ==="
          find ${GITHUB_WORKSPACE}/config -name "*.overlay" -type f
          echo "=== Contenido del overlay sofle ==="
          cat ${GITHUB_WORKSPACE}/config/boards/shields/sofle/sofle.overlay || true

      - name: Build LEFT (with PIM447)
        run: |
          west build -s zmk/app -b nice_nano_v2 -d build/left -- \
            -DSHIELD="sofle_left" \
            -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
        
      - name: Build RIGHT (with OLED)
        run: |
          west build -s zmk/app -b nice_nano_v2 -d build/right -- \
            -DSHIELD="sofle_right nice_oled" \
            -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
        
      - name: Verify PIM447
        run: |
          echo "=== Verificando PIM447 ==="
          if [ -f build/left/zephyr/zephyr.dts ]; then
            grep -n "pim447" build/left/zephyr/zephyr.dts && echo "✅ PIM447 encontrado" || echo "❌ PIM447 no encontrado"
          else
            echo "DTS file not found"
          fi
        
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/left/zephyr/zmk.uf2
            build/right/zephyr/zmk.uf2