name: Build Sofle with Pimoroni

on:
  push:
    paths:
      - "build.yaml"
      - "config/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/zmkfirmware/zmk-build-arm:2.5
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Initialize workspace (west init)
        run: west init -l app
      - name: Update modules (west update)
        run: west update
      - name: Export Zephyr CMake package (west zephyr-export)
        run: west zephyr-export
      - name: Sanity check - verify paths
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "ZMK app directory:"
          ls -la zmk/app/ || echo "zmk/app/ not found"
          echo "Config directory:"
          ls -la config/
      - name: Build Sofle left with Pimoroni
        run: west build -s app -b nice_nano_v2 -d build/sofle_left -- -DSHIELD=sofle_left -DZMK_CONFIG=${GITHUB_WORKSPACE}/config -DCONFIG_ZMK_MOUSE=y
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: sofle-left-pimoroni-zmk
          path: build/zephyr/zmk.uf2